### ISSUE TITLE
add sudo to npm install.

### ISSUE THREAD

**Issue by zyxep** [nodecg/nodecg.com#2]
Hi.

FYI it doesn't work when you run it as a user :) had to run it under sudo or as root.

**Comment by Lange** [comment]
I assume you're talking `npm install -g nodecg-cli`?

The sudo-ness of this command depends on the users envrionment. Not everyone will need sudo.

@MattMcNam Do you think we should add a note of some kind about this?

**Comment by MattMcNam** [comment]
I think a little note under the commands like
"EACCESS errors? [Read this](https://docs.npmjs.com/getting-started/fixing-npm-permissions)"
might work well.

**Comment by Lange** [comment]
Fixed by 201fe72
